#!/usr/bin/env python3
"""gen_elf_tests.py — part of the moonshot operating system.

Copyright (C) 2026 tavro

This file is part of moonshot, an operating system built from scratch.
moonshot is free software, distributed under the GNU General Public
License version 3 or (at your option) any later version, WITHOUT ANY
WARRANTY; see the LICENSE file for the full text.

Compiles every program in elf_tests/ with `coff --elf` and writes
elf_tests_data.c0, which bakes the resulting ELF images into the kernel as
byte literals and installs them onto jakel at first boot.

Why baked in rather than copied onto the disk: Moonshot has no way to receive
a file from the host. Everything a ring-3 program needs to exist as a file has
to be seeded by the kernel itself, the same way demo.c0, hello.elf and
gnista.elf already are. This script just automates the pattern that was
previously done by hand, once per test program.

The point of the suite is that coff0.c implements only the text backend, so
c0-coff's differential tests prove nothing about the machine-code backend
every ring-3 binary is actually built through. Three separate silent-wrong-
code bugs were found in that backend by eye, one at a time. These programs
each compute a value that only comes out right if codegen is correct, and
return it as an exit code the kernel prints to serial.

Run via verify_elf_backend.sh, which regenerates, rebuilds and runs them.
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTS = os.path.join(HERE, "elf_tests")
COFF = os.path.join(HERE, "..", "c0-coff", "coff1")
OUT = os.path.join(HERE, "elf_tests_data.c0")

HEADER = """// elf_tests_data.c0 — part of the moonshot operating system.
//
// Copyright (C) 2026 tavro
//
// This file is part of moonshot, an operating system built from scratch.
// moonshot is free software, distributed under the GNU General Public
// License version 3 or (at your option) any later version, WITHOUT ANY
// WARRANTY; see the LICENSE file for the full text.
//
// GENERATED by gen_elf_tests.py from elf_tests/*.c0 -- do not edit by hand.
//
// Each program below was compiled with `coff --elf` and is seeded onto jakel
// as etNN.elf. They exist to give coff's machine-code backend a real
// verification story: coff0.c implements only the text backend, so the
// differential test suite proves nothing about the path every ring-3 binary
// is built through. Each program returns a value that is only correct if
// codegen is correct; verify_elf_backend.sh spawns them and checks the exit
// codes the kernel prints to serial.
"""


def emit_bytes(name, data):
    out = ["int seed_%s_size() { return %d; }" % (name, len(data))]
    out.append("void seed_%s(int buf) {" % name)
    out.append("    int p = 0;")
    # 8 bytes at a time, matching the existing hand-generated seed files.
    i = 0
    while i + 8 <= len(data):
        word = int.from_bytes(data[i:i + 8], "little")
        out.append("    store64(buf + p, 0x%016x); p = p + 8;" % word)
        i += 8
    while i < len(data):
        out.append("    store8(buf + p, %d); p = p + 1;" % data[i])
        i += 1
    out.append("    return;")
    out.append("}")
    return out


def main():
    if not os.path.isdir(TESTS):
        sys.exit("no elf_tests/ directory at %s" % TESTS)
    if not os.access(COFF, os.X_OK):
        sys.exit("coff1 not built at %s -- run build.sh first" % COFF)

    sources = sorted(f for f in os.listdir(TESTS) if f.endswith(".c0"))
    if not sources:
        sys.exit("elf_tests/ has no .c0 programs")

    lines = [HEADER]
    installs = []
    manifest = []

    for idx, src in enumerate(sources, start=1):
        path = os.path.join(TESTS, src)
        with open(path) as f:
            text = f.read()
        m = re.search(r"^//\s*expect:\s*(-?\d+)\s*$", text, re.M)
        if not m:
            sys.exit("%s has no `// expect: N` line" % src)
        expect = int(m.group(1))

        elf = os.path.join(TESTS, os.path.splitext(src)[0] + ".elf")
        r = subprocess.run([COFF, "--elf", path, elf],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("coff --elf failed on %s:\n%s%s" % (src, r.stdout, r.stderr))
        with open(elf, "rb") as f:
            data = f.read()
        os.remove(elf)

        name = "et%02d" % idx
        lines.append("")
        lines.append("// %s -- %s, expects exit code %d" % (name, src, expect))
        lines.extend(emit_bytes(name, data))
        installs.append((name, len(data)))
        manifest.append((name, src, expect))

    # One install function so jakel.c0 needs a single call and never changes
    # when a test is added or removed.
    lines.append("")
    lines.append("// Seeds every test ELF into directory `dir`. Any stale copy is removed")
    lines.append("// first: disk.img survives reboots, so a rebuilt test would otherwise")
    lines.append("// be silently ignored in favour of the previous run's bytes. Called on")
    lines.append("// EVERY boot from jakel_init, not just the first -- see the fixture")
    lines.append("// section there for why that placement is load-bearing.")
    lines.append("void seed_elf_tests_install(int dir) {")
    for name, size in installs:
        lines.append("    int stale_%s = jakel_lookup(dir, \"%s.elf\");" % (name, name))
        lines.append("    if (stale_%s >= 0) { jakel_remove(stale_%s); }" % (name, name))
        lines.append("    int f_%s = jakel_make_file(dir, \"%s.elf\");" % (name, name))
        lines.append("    if (f_%s >= 0) {" % name)
        lines.append("        int b_%s = kmalloc(%d);" % (name, size))
        lines.append("        if (b_%s != 0) {" % name)
        lines.append("            seed_%s(b_%s);" % (name, name))
        lines.append("            jakel_write(f_%s, 0, b_%s, %d);" % (name, name, size))
        lines.append("            kfree(b_%s);" % name)
        lines.append("        }")
        lines.append("    }")
    lines.append("    return;")
    lines.append("}")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    # The runner reads this to know what to spawn and what to expect.
    with open(os.path.join(TESTS, "manifest.txt"), "w") as f:
        for name, src, expect in manifest:
            f.write("%s %s %d\n" % (name, src, expect))

    print("generated %s from %d programs" % (os.path.basename(OUT), len(manifest)))
    for name, src, expect in manifest:
        print("  %s.elf  %-24s expect %d" % (name, src, expect))


if __name__ == "__main__":
    main()
