#!/usr/bin/env python3
"""gen_seed.py — part of the moonshot operating system.

Copyright (C) 2026 tavro

This file is part of moonshot, an operating system built from scratch.
moonshot is free software, distributed under the GNU General Public
License version 3 or (at your option) any later version, WITHOUT ANY
WARRANTY; see the LICENSE file for the full text.

Turns a binary file into a c0 source file that writes those bytes into a
buffer -- the way every ring-3 program Moonshot ships gets onto the
filesystem. Moonshot has no way to receive a file from the host, so anything
that has to exist as a file is baked into the kernel and written out by
jakel_init on first boot.

Emits:
    int seed_<name>_size() { return N; }
    void seed_<name>(int buf) { ... }

Usage:
    gen_seed.py <input-binary> <name> <output.c0> [description...]

An earlier version of this script generated the existing *_data.c0 files but
was never checked in, so the generated files could not be regenerated when
their source changed. This one is checked in. gen_elf_tests.py does the same
job for the whole elf_tests/ suite at once and shares the byte-emitting
shape; this one stays for the single-file cases (Gnista's demo, the alloc and
ticks probes).
"""

import os
import sys


def emit(data, name):
    out = []
    out.append("int seed_%s_size() { return %d; }" % (name, len(data)))
    out.append("void seed_%s(int buf) {" % name)
    out.append("    int p = 0;")
    i = 0
    # 8 bytes at a time; c0 has store64 and store8, so the tail goes byte
    # by byte rather than padding the buffer out to a multiple of 8.
    while i + 8 <= len(data):
        word = int.from_bytes(data[i:i + 8], "little")
        out.append("    store64(buf + p, 0x%016x); p = p + 8;" % word)
        i += 8
    while i < len(data):
        out.append("    store8(buf + p, %d); p = p + 1;" % data[i])
        i += 1
    out.append("    return;")
    out.append("}")
    return out


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__.strip().splitlines()[-6].strip())
    src, name, dst = sys.argv[1], sys.argv[2], sys.argv[3]
    desc = " ".join(sys.argv[4:])

    with open(src, "rb") as f:
        data = f.read()

    lines = [
        "// %s — part of the moonshot operating system." % os.path.basename(dst),
        "//",
        "// Copyright (C) 2026 tavro",
        "//",
        "// This file is part of moonshot, an operating system built from scratch.",
        "// moonshot is free software, distributed under the GNU General Public",
        "// License version 3 or (at your option) any later version, WITHOUT ANY",
        "// WARRANTY; see the LICENSE file for the full text.",
        "//",
        "// GENERATED by gen_seed.py from %s (%d bytes) -- do not edit by hand."
        % (os.path.basename(src), len(data)),
    ]
    if desc:
        lines.append("//")
        for line in desc.split("\n"):
            lines.append("// %s" % line)
    lines.append("")
    lines.extend(emit(data, name))
    lines.append("")

    with open(dst, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d bytes of %s)" % (dst, len(data), os.path.basename(src)))


if __name__ == "__main__":
    main()
