#!/usr/bin/env python3
# gen_sprite.py — part of gnista, a game engine for the moonshot operating system.
#
# Copyright (C) 2026 tavro
#
# This file is part of gnista, a game engine written in c0 for moonshot.
# gnista is free software, distributed under the GNU General Public
# License version 3 or (at your option) any later version, WITHOUT ANY
# WARRANTY; see the LICENSE file for the full text.
#
# Generates a small 2-frame circular sprite (12x12, BGR0 pixel format,
# color 0 = transparent -- matching Moonshot's SYS_BLIT expectation) as a
# c0 seed_sprite_demo(buf) function, same store64/store8-literal pattern
# gen_seed.py uses for whole ELF binaries.
import sys, math

W = H = 12
FRAMES = 2
# frame 0: orange circle. frame 1: yellow circle (simple two-color "twinkle").
COLORS = [(0, 140, 255), (0, 220, 255)]  # (B, G, R) per frame

def frame_pixels(r, g, b):
    cx = cy = (W - 1) / 2.0
    radius = W / 2.0 - 0.5
    out = bytearray()
    for y in range(H):
        for x in range(W):
            dx = x - cx
            dy = y - cy
            if dx * dx + dy * dy <= radius * radius:
                out += bytes([b, g, r, 0])
            else:
                out += bytes([0, 0, 0, 0])  # transparent
    return out

data = bytearray()
for (b, g, r) in COLORS:
    data += frame_pixels(r, g, b)

out_path = sys.argv[1] if len(sys.argv) > 1 else "sprite_demo_data.c0"
lines = []
lines.append("// sprite_demo_data.c0 — part of gnista, a game engine for the moonshot operating system.")
lines.append("//")
lines.append("// Copyright (C) 2026 tavro")
lines.append("//")
lines.append("// This file is part of gnista, a game engine written in c0 for moonshot.")
lines.append("// gnista is free software, distributed under the GNU General Public")
lines.append("// License version 3 or (at your option) any later version, WITHOUT ANY")
lines.append("// WARRANTY; see the LICENSE file for the full text.")
lines.append("//")
lines.append(f"// GENERATED by gen_sprite.py -- do not edit by hand. A {W}x{H}, {FRAMES}-frame")
lines.append("// circular sprite (BGR0 pixels, color 0 = transparent), baked into the")
lines.append("// program's own compiled ELF rather than loaded from a file at runtime,")
lines.append("// the same way the kernel bakes in the programs themselves.")
lines.append(f"int seed_sprite_demo_size() {{ return {len(data)}; }}")
lines.append("void seed_sprite_demo(int buf) {")
lines.append("    int p = 0;")

i = 0
n = len(data)
while i + 8 <= n:
    chunk = int.from_bytes(data[i:i+8], "little")
    lines.append(f"    store64(buf + p, 0x{chunk:016x}); p = p + 8;")
    i += 8
while i < n:
    lines.append(f"    store8(buf + p, {data[i]}); p = p + 1;")
    i += 1

lines.append("}")
lines.append("")

with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"wrote {out_path}: {len(data)} bytes ({W}x{H}x{FRAMES} BGR0)")
